1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

In [11]:
import numpy as np

arr1 = np.random.randint(1, 21, (5,5))

arr1[:,2] = 1

arr1

array([[20, 19,  1,  2, 10],
       [ 4, 15,  1, 18, 20],
       [ 8, 13,  1, 18,  3],
       [ 7, 17,  1,  6,  5],
       [ 5, 19,  1, 11, 15]])

Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [16]:
import numpy as np

arr2 = np.random.randint(1, 17, (4,4))

np.fill_diagonal(arr2, 0)

arr2

array([[ 0, 11,  4,  3],
       [11,  0, 15, 14],
       [16,  1,  0, 12],
       [10, 10, 12,  0]])

Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [31]:
arr3 = np.arange(1,37).reshape(6,6)

sub_arr3 = arr3[2:5, 1:4]

print(arr3)

print("\n", sub_arr3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

 [[14 15 16]
 [20 21 22]
 [26 27 28]]


Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [12]:
arr4_1 = np.random.randint(1,5, (3,4))
arr4_2 = np.random.randint(1,5, (3,4))

Addtion = arr4_1 + arr4_2
Subration = arr4_1 - arr4_2
Multiplication = arr4_1 * arr4_2
division = np.divide(arr4_1, arr4_2)

print(Addtion)
print("\n", Subration)
print("\n", Multiplication)
print("\n", division)


[[4 4 6 6]
 [2 3 5 4]
 [4 3 5 2]]

 [[ 2  0  2  0]
 [ 0 -1  3  2]
 [-2  1 -3  0]]

 [[3 4 8 9]
 [1 2 4 3]
 [3 2 4 1]]

 [[3.         1.         2.         1.        ]
 [1.         0.5        4.         3.        ]
 [0.33333333 2.         0.25       1.        ]]


Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [21]:
arr5 = np.random.randint(1,17, (4,4))

print(arr5)

row_sum = np.sum(arr5, axis=1)
col_sum = np.sum(arr5, axis=0)

print("\n",row_sum)
print("\n",col_sum)

[[ 6  8 10  2]
 [13 10  2  3]
 [ 8 16  9 16]
 [11 12 11 10]]

 [26 28 49 44]

 [38 46 32 31]


Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [24]:
arr6 = np.random.randint(1,14, (5,5))
print(arr6)

mean = np.mean(arr6)
median = np.median(arr6)
standard_deviation = np.std(arr6)
variance = np.var(arr6)

print("\n", mean)
print("\n", median)
print("\n", standard_deviation)
print("\n", variance)

[[12  7  7 12 10]
 [ 5 11  8  7  6]
 [11 12  7  8  6]
 [ 3 10 11  2  5]
 [ 5  5  9  2  5]]

 7.44

 7.0

 3.034205002962061

 9.2064


Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
arr7 = np.random.randint(1,10, (3,3))


mean = np.mean(arr7)
standard_deviation = np.std(arr7)

# Normalize the array: (X - mean) / std_dev

Normalize = (arr7 - mean)/standard_deviation

print(Normalize)

[[-1.02247472 -1.82267232  0.97801929]
 [ 0.17782169  0.17782169  0.57792049]
 [-1.02247472  1.3781181   0.57792049]]


Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

Broadcasting is a powerful feature in NumPy that allows operations between arrays of different shapes without explicitly reshaping them. Instead of manually repeating elements to match the shape, NumPy automatically expands the smaller array to make the operation possible.



In [30]:
arr8 = np.random.randint(1,13, (3,3))
arr8_1 = np.random.randint(1,13, (3,))

print(arr8)
print("\n", arr8_1)

arr8_new = arr8 + arr8_1

print("\n", arr8_new)

[[11  6 12]
 [ 5  4  6]
 [11  7  4]]

 [9 1 8]

 [[20  7 20]
 [14  5 14]
 [20  8 12]]


Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [31]:
arr9 = np.random.randint(1,11, (4,4))
arr9_1 = np.random.randint(1,11, (4,))

arr9_new = arr9 - arr9_1

print(arr9_new)

[[-2 -3  4  7]
 [-2 -4  6  2]
 [-6  3  0  7]
 [-2 -3  7  1]]


Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [32]:
arr10 = np.random.randint(1,11, (3,3))

determinant = np.linalg.det(arr10)
inverse = np.linalg.inv(arr10)
eigenvalues = np.linalg.eigvals(arr10)

print(determinant)
print("\n", inverse)
print("\n", eigenvalues)



-131.99999999999997

 [[ 0.27272727 -0.03030303 -0.01515152]
 [-0.04545455 -0.10606061  0.1969697 ]
 [-0.04545455  0.22727273 -0.13636364]]

 [ 3.52786405 12.47213595 -3.        ]


Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [34]:
arr11 = np.random.randint(1,11, (2,3))
arr11_1 = np.random.randint(1,11, (3,2))

arr11_new = np.linalg.multi_dot([arr11, arr11_1])

print(arr11_new)

[[116  69]
 [ 88  42]]


Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [38]:
arr12 = np.random.randint(1,9, (3,3)).reshape(1,9)

print(arr12)

arr12_new = arr12.reshape(9,1)

print("\n", arr12_new)

[[7 2 1 5 1 3 2 2 3]]

 [[7]
 [2]
 [1]
 [5]
 [1]
 [3]
 [2]
 [2]
 [3]]


Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [45]:
arr13 = np.random.randint(1,6, (5,5))

flatten = arr13.flatten()

print(flatten)
print("\n", arr13.reshape(5,5))

[5 2 2 1 3 5 2 4 4 2 3 3 1 5 2 5 2 4 3 1 4 2 5 5 3]

 [[5 2 2 1 3]
 [5 2 4 4 2]
 [3 3 1 5 2]
 [5 2 4 3 1]
 [4 2 5 5 3]]


Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [8]:
arr14 =  np.random.randint(1,11, (5,5))
print(arr14)

arr14_new = arr14[[0,0,4,4],[0,4,0,4]]

print("\n", arr14_new)


[[ 4  9 10  1  7]
 [10  7  3 10  4]
 [ 8  4  8  4  9]
 [ 9 10  5  1  9]
 [ 8  5  7  1  9]]

 [4 7 8 9]


In [6]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Select rows at indices 0 and 2
result = matrix[[0, 2]]

print(result)

[[1 2 3]
 [7 8 9]]


Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [10]:
arr15 = np.random.randint(1,13, (4,4))
print(arr15)

condition = arr15 > 10

kya_baat_hai = arr15[condition]

print("\n", kya_baat_hai)

[[ 2 11 10  9]
 [ 9  3  6  5]
 [ 6  1  2  6]
 [ 1 10  2  2]]

 [11]


Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [18]:
person_dtype = np.dtype([
    ('name', 'U10'),   # Unicode string of max length 10
    ('age', 'i4'),     # 32-bit integer
    ('weight', 'f4')   # 32-bit float
])

# Create a structured array with some data
people = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 30, 70.2),
    ('Charlie', 22, 68.0),
    ('David', 28, 72.1)
], dtype=person_dtype)

# Sort the array by the 'age' field
sorted_people = np.sort(people, order='age')

# Print results
print("Original Data:")
print(people)

print("\nSorted by Age:")
print(sorted_people)

Original Data:
[('Alice', 25, 55.5) ('Bob', 30, 70.2) ('Charlie', 22, 68. )
 ('David', 28, 72.1)]

Sorted by Age:
[('Charlie', 22, 68. ) ('Alice', 25, 55.5) ('David', 28, 72.1)
 ('Bob', 30, 70.2)]


Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

Euclidean Distance is the straight-line distance between two points in space — like using a ruler to measure the shortest distance between two locations.

In [25]:
arr_data = np.dtype([
    ('X', 'int'),
    ('Y', 'int')
])

added_data = np.array([
    (23,34),
    (34,45),
    (45,67)
], dtype=arr_data)

print(added_data)

distance = np.sqrt(added_data['X']**2 + added_data['Y']**2)

print("\n", distance)

[(23, 34) (34, 45) (45, 67)]

 [41.0487515  56.40035461 80.7093551 ]


Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [36]:
arr16 = np.random.randint(1,20, (4,4))
print(arr16)

masked_arr16 = np.ma.masked_where(arr16 > 10, arr16)
print("\n",masked_arr16)

sum_unmasked = masked_arr16.sum()
print("\n", sum_unmasked)


[[ 7 11  2 12]
 [14 12 16 14]
 [12 18 17 16]
 [ 5  7 16  3]]

 [[7 -- 2 --]
 [-- -- -- --]
 [-- -- -- --]
 [5 7 -- 3]]

 24


Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [38]:


# Step 1: Create a 3x3 array with random integers
arr = np.random.randint(1, 21, (3, 3))
print("Original Array:")
print(arr)

# Step 2: Create a mask for diagonal elements
mask = np.eye(3, dtype=bool)

# Step 3: Create the masked array
masked_arr = np.ma.array(arr, mask=mask)
print("\nMasked Array (diagonal elements masked):")
print(masked_arr)

# Step 4: Compute mean of unmasked elements
mean_unmasked = masked_arr.mean()
print("\nMean of unmasked elements:", mean_unmasked)

# Step 5: Replace masked (diagonal) elements with the mean
filled_arr = masked_arr.filled(mean_unmasked)
print("\nFinal Array (masked values replaced with mean):")
print(filled_arr)


Original Array:
[[13 10  2]
 [17 17 11]
 [18  6 18]]

Masked Array (diagonal elements masked):
[[-- 10 2]
 [17 -- 11]
 [18 6 --]]

Mean of unmasked elements: 10.666666666666666

Final Array (masked values replaced with mean):
[[10 10  2]
 [17 10 11]
 [18  6 10]]
